baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vibetracker Documentation'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/CamdenClark/vibetracker'
